apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 2223
      targetPort: 2223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
            - configMapRef:
                name: user-env
          image: "krixlion/dev_forum-user:0.1.0"
          imagePullPolicy: IfNotPresent
          name: server
          ports:
            - name: grpc
              containerPort: 50051
            - name: metrics
              containerPort: 2223
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
            requests:
              cpu: 5m
              memory: 80Mi
          volumeMounts:
            - name: tls-certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-secret-user
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-user
spec:
  secretName: tls-secret-user
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - key encipherment
    - digital signature
  dnsNames:
    - "user-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
