resources:
  - ../../base
  - dev-volume.yaml

namespace: dev

replicas:
  - name: user-d
    count: 1

images:
  - name: krixlion/dev_forum-user
    newName: krixlion/go-reflex-dlv
    newTag: latest

patches:
  - path: deployment-patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: user-d

  - path: service-patches.yaml
    target:
      version: v1
      kind: Service
      name: user-service

configMapGenerator:
  - name: user-env
    env: user.properties
