name: Run integration tests on Kind cluster

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kind Cluster
        uses: helm/kind-action@v1.10.0
            
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and load Docker image to Kind
        run: |
          docker build -t mymicroservice:latest .
          kind load docker-image mymicroservice:latest

      - name: Run tests
        run: |
          make k8s-integration-test args="timeout=3s"
