name: Run integration tests on Kind cluster

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: testing
        
      - name: Checkout code at repo root
        uses: actions/checkout@v4.1.4
      
      - name: Build and load Docker image to Kind
        run: |
          cp .env.example .env
          docker build . -t krixlion/dev_forum-user:latest -f deployment/Dockerfile --target test
          kind load docker-image krixlion/dev_forum-user:latest --name "testing"
      
      - name: Deploy service
        run: |
          # Add namespace if it does not exist.
          kubectl create namespace test --dry-run=client -o yaml | kubectl apply -f -
          make k8s-run overlay=test

      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1

      - name: Run tests
        run: |
          make k8s-integration-test overlay=test args="timeout=3s"
